config/routes.rb
Rails.application.routes.draw do
  
  resources :appointments, execpt: [:index]
  resources :patients, except: [:index]
  resources :doctors, only: [:index, :show]
  
  root 'doctors#index'
  delete '/sessions/logout', to: 'sessions#logout', as: 'logout'
  get '/sessions/new', to: 'sessions#new', as: 'new_login'
  post '/sessions/create', to: 'sessions#create', as: 'login'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
   belongs_to :patient
   belongs_to :doctor

   validates :patient_id, presence: true
   validates :doctor_id, presence: true
   validates :condition, :length => {:minimum => 3}, allow_blank: false
   validates :additional_info, :length => { :minimum => 5, :maximum => 250 }, allow_blank: false
   validates :date, presence: true
   validates :time, presence: true

end

app/models/doctor.rb
class Doctor < ApplicationRecord
  has_many :appointments
  has_many :patients, through: :appointments

  validates :name, presence: true
  validates :name, uniqueness: true
  validates :birthday, presence: true
  validates :specialty, presence: true
  validates :city, presence: true
  validates :zipcode, :length => { :minimum => 5, :maximum => 6 }, :numericality => true, allow_blank: true
  validates_each :birthday do |record, attr, value|
    record.errors.add attr, "is not a valid date. You must be at
least 16 year old to sign in." if value > Date.new((Date.today.year -
18),(Date.today.month),(Date.today.day))
  end

end

app/models/patient.rb
class Patient < ApplicationRecord
  has_many :appointments
  has_many :doctors, through: :appointments

  has_secure_password
  validates :name, presence: true
  validates :name, uniqueness: true
  validates :birthday, presence: true
  validates :city, presence: true
  validates :zipcode, :length => { :minimum => 5, :maximum => 6 }, :numericality => true, allow_blank: true
  validates_each :birthday do |record, attr, value|
    record.errors.add attr, "is not a valid date. You must be at
least 16 year old to sign in." if value > Date.new((Date.today.year -
18),(Date.today.month),(Date.today.day))
  end

  def calc_age
    Time.now.year - self.birthday.year
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :set_current_user
   before_action :authorized

   def set_current_user
      @current_user = Patient.find_by(id: session[:user_id])
   end

   def authorized
      redirect_to root_path unless set_current_user
   end   
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
   before_action :find_appointment, only: [:show, :edit, :update, :destroy]

   def index
      @appointments = Appointment.all
   end

   def new
      @appointment = Appointment.new
      
      unless params[:zipcode].blank?
         redirect_to doctors_path(@doctors, zipcode: params[:zipcode])
      end
   end

   def show
   end

   def create
      # patient_id = session[:user_id]
      @appointment = @current_user.appointments.create(appointments_params)
      redirect_to patient_path(@appointment.patient)
   end

   def edit
   end

   def update
      @appointment.update(appointments_params)
      redirect_to appointment_path(@appointment)
   end

   def destroy
      @appointment.destroy
      redirect_to appointments_path
   end


   private

   def appointments_params
      params.require(:appointment).permit(:doctor_id, :condition, :date, :time, :additional_info)
   end

   def find_appointment
      @appointment = Appointment.find(params[:id])
   end

end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :find_doctor, only: [:show]
  skip_before_action :authorized, only: [:index, :show]

  def index
    @doctors = Doctor.all
    unless params[:zipcode].blank?
      @doctors = @doctors.where(zipcode: params[:zipcode])
    end
  end
  

  def show
    unless params[:zipcode].blank?
      redirect_to doctors_path(@doctors, zipcode: params[:zipcode])
    end
  end
 
  private

  def find_doctor
    @doctor = Doctor.find(params[:id])
  end

end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :find_patient, only: [:show, :edit, :update, :destroy]
  skip_before_action :authorized, only: [:new, :create]

  def index
    @patients = Patient.all
  end

  def show
    unless params[:zipcode].blank?
      redirect_to doctors_path(@doctors, zipcode: params[:zipcode])
    end
  end

  def new
    @patient = Patient.new
    unless params[:zipcode].blank?
      redirect_to doctors_path(@doctors, zipcode: params[:zipcode])
    end
  end

  def create
    patient = Patient.create(patient_params)
    if patient.valid?
      session[:user_id] = patient.id
      redirect_to patient
    else
      flash[:my_error] = patient.errors.full_messages
      redirect_to new_patient_path
    end
  end

  def edit
  end

  def update
    @patient.update(patient_params)
    redirect_to patient_path(@patient)
  end

  def destroy
    @patient.destroy
    redirect_to '/'
  end

  private

  def patient_params
    params.require(:patient).permit(:name, :password, :birthday, :city, :zipcode, :address, :state)
  end

  def find_patient
    @patient = Patient.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
   skip_before_action :authorized
   def logout
      session.delete(:user_id)
      cookies.delete(session[:user_id])
      redirect_to root_path
   end

   def new
   end

   def create
      patient = Patient.find_by(name: params[:session][:name])

      if patient && patient.authenticate(params[:session][:password])
         session[:user_id] = patient.id
         redirect_to patient
      else
         flash[:my_error] = "Name or Password is Incorrect"
         redirect_to new_login_path
      end
   end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/appointments/_form.html.erb
<%= form_for @appointment do |f| %>

   <%= f.label :condition %>
   <%= f.text_field :condition %>
   <br>
   <%= f.label :additional_info %>
   <%= f.text_field :additional_info, :size => "50x50", placeholder: "Tell us more..."%>
   <br>
   <%= f.label :doctor_id %>
   <%= f.select :doctor_id, options_from_collection_for_select(Doctor.order(:name).all, "id", "name", params[:doctor_id]) %>
   <br>
   <%= f.label :date %>
   <%= f.date_field(:date, min: Date.today, order: [:month, :day, :year])%>
   <br>
   <%= f.label :time %>
   <%= f.time_field(:time, min:"9:00", max:"20:00",minute_step: 15) %>                           
                           
   <br>
   <%= f.submit %>
<% end %>

app/views/appointments/edit.html.erb
<h2>Edit your appointment</h2>

<%= render 'form' %>

app/views/appointments/index.html.erb
<h2>These are all the appointments:</h2>

<% @appointments.each do |appointment| %>
   <p><h4>Patient Name: <%= link_to appointment.patient.name, patient_path(appointment.patient) %></h4><h6>Reasoning: "<%= link_to appointment.condition, appointment_path(appointment) %>"</h6>time: <%= appointment.time %></p>
<%end%>

app/views/appointments/new.html.erb
<h2>New Appointment for <%= @current_user.name %></h2>

<%= render 'form'%>

app/views/appointments/show.html.erb
<br>
<h3>Upcoming Appointment: </h3>
<h4>Dr <%= @appointment.doctor.name %><h4>
<%= image_tag '6.jpg' %>

<h5>Patient Condition: </h5>
<%= @appointment.condition %>
<br>
<br>
<h5>Additional information:</h5>
<%= @appointment.additional_info %>
<br>
<br>
<h5>Apointment Date & Time: </h5>
<%= @appointment.date.strftime("%B %-d, %Y") %>, <%= @appointment.time.strftime("%l:%M %P") %></h3>


<br>
<br>
<br>
<p>Click <%= link_to 'here', edit_appointment_path(@appointment) %> to edit to your appointment.</p>

app/views/doctors/index.html.erb
<br>
<h2> Available Doctors </h2>

<br>
<br>
<% @doctors.order(:specialty).each do |d| %>
  <p><b>Doctors name: </b><%= link_to d.name, doctor_path(d) %>
  <br>
  <b>Specialty:</b> <%= d.specialty %></p>
  <br>
<%end%>

app/views/doctors/show.html.erb
<br>
<h3>Dr. <%= @doctor.name %></h3>
<h4><%= @doctor.specialty %></h4>
<br>
<h6>
<%= image_tag "#{rand(1..5)}.jpg"%>
<br>
<br>
   <%= @doctor.address%><br>
   <%= @doctor.city %>, <%= @doctor.state %> <%= @doctor.zipcode %>
</h6>

<br>
<p>This doctor has <b><%= @doctor.patients.count %></b> patients
<%#<p> Here are a list of my patients: </p>
<%# @doctor.patients.uniq.each do |p| %>
<%# = link_to p.name, patient_path(p)%>
<%#end%>
<br>
<% if @current_user %>
   <p>Click <%= link_to 'here', new_appointment_path(:doctor_id => @doctor.id) %> to book an appointment.</p>
<%end%>
<br>
<%# <h6>Edit your doctor's profile <%= link_to "here", edit_doctor_path(@doctor) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>nbdMD</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar sticky-top navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
      <a class="navbar-brand" href="/">nbdMD</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <div class="navbar-nav">
        <ul class="navbar-nav mx-auto">
          <a class="nav-link active" href="/">Home <span class="sr-only">(current)</span></a>

          <%#<a class="nav-link" href="/doctors/new">Find a Doctor</a> %>
          
          <a class="nav-link" href="/appointments/new">Create an Appointment</a>
          <% if @current_user %>
            <a> <%= link_to 'My Profile', patient_path(@current_user), class: "nav-link" %> </a>
          <% else %>
            <a> <%= link_to 'My Profile', new_patient_path, class: "nav-link" %> </a>
          <%end%>
        </ul>  
        </div>
      </div>
    
      <%= form_with(path: root_path, method: "get", class: "form-inline my-2 my-lg-0") do %>
        <div class: "form-control mr-sm-2">
          <%= label_tag(:q, "") %>
          <%= text_field_tag(:zipcode, "", class: 'form-control mr-sm-2') %>
        </div>
        <%= submit_tag("Search By Zip", class: "btn btn-light bg-primary my-2 my-sm-0") %>
      <% end %>

      <div class="navbar-nav">
        <div class="nav-item">
        <% if @current_user %>
        <ul class="navbar-nav mx-auto">
          <li class="nav-link">Welcome <%= @current_user.name %></li>
          <li> <%= button_to 'Logout', logout_path, method: :delete, class:"btn btn-light bg-primary my-2 my-sm-0"  %></li>
        </ul>
        <%else%>
        <ul class="navbar-nav mx-auto">
          <li> <%= button_to 'Login', new_login_path, method: :get, class: "btn btn-light bg-primary my-2 my-sm-0" %></li>
          <li> <%= button_to 'Sign Up', new_patient_path, method: :get, class: "btn btn-light bg-primary my-2 my-sm-0" %></li>
        </ul>
        <%end%>
        </div>
      </div>
    </nav>

    <div class="container">
      <div class="column">
        <%= yield %>
      </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>

app/views/patients/_form.html.erb
<% if flash[:my_error] %>
  <% flash[:my_error].each do |error| %>
    <p><%= error %></p>
  <%end%>
<%end%>

<%= form_for @patient, :html => {:class => "form-horizontal center"} do |f| %>
      <div class="form-group">
        <%= f.label :name, "name:", class: "col-md-4 control-label" %>
        <div class="col-md-8">
          <%= f.text_field :name, class: "form-control", required: true %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :password, "password:", class: "col-md-4 control-label" %>
        <div class="col-md-8">
          <%= f.password_field :password, class: "form-control", required: true %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :birthday, "birthday:", class: "col-md-4 control-label" %>
        <div class="col-md-8">
          <%= f.date_select :birthday, :start_year => 1900, end_year: Date.today.year - 18, class: "form-control", :order => [:month, :day, :year] %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :address, "address:", class: "col-md-4 control-label" %>
        <div class="col-md-8">
          <%= f.text_field :address, class: "form-control", required: true %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :city, "city:", class: "col-md-4 control-label" %>
        <div class="col-md-8">
          <%= f.text_field :city, class: "form-control", required: true %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :state, "state:", class: "col-md-4 control-label" %>
        <div class="col-md-8">
          <%= f.text_field :state, class: "form-control", required: true %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :zipcode, "zip-code:", class: "col-md-4 control-label" %>
        <div class="col-md-8">
          <%= f.text_field :zipcode, class: "form-control" %>
        </div>
      </div>

      <%= f.submit "Submit", class: "btn btn-default btn-primary" %>  
<% end %>

app/views/patients/edit.html.erb
<h2>Edit Profile</h2>

<%= render 'form' %><br>
<%= button_to "Delete Patient", @patient, method: :delete %>

app/views/patients/new.html.erb
<h2>New patient form</h2>

<%= render 'form' %>

app/views/patients/show.html.erb
<br>
<h3><%= @patient.name %></h3>
   <h5>
    <%= @patient.address%>
    <br>
    <%= @patient.city %>, <%= @patient.state %> <%= @patient.zipcode %>
   </h5>
   <br>
   <b>Birthdate:</b> <%= @patient.birthday.strftime("%B %-d, %Y") %><br>
   <b>Age:</b> <%= @patient.calc_age %>
<br>
<br>
<br>
  <h5> My upcoming Appointments: </h5>
<br>

<% @patient.appointments.each do |appointment| %>
  <p><b>Doctor: </b><%= link_to appointment.doctor.name, doctor_path(appointment.doctor) %></p><p><b>Reason:</b>"<%= link_to appointment.condition, appointment_path(appointment) %>"</p>
  <p><b>Date: </b><%= appointment.date.strftime("%B %-d, %Y") %> <b>at:</b> <%= appointment.time.strftime("%l:%M %P") %> </p><br> 
<%end%>

<%#  if @appointment.time 
  <p>time: = appointment.time.strftime("%H:%M") </p>
end -
%>
<br>

<br>
<p>Changed your information? Update <%= link_to "here", edit_patient_path(@patient) %>.</p>